### ISSUE TITLE
Freshsheet posting/sending form

### ISSUE THREAD

**Issue by ckcollab** [BrendanMyers88/EverFresh#1]
- [ ] A "header message" textarea for the top of the email
- [ ] A list of food items with checkboxes. The food items should be displayed in categories exactly how they would be on the freshsheet
- [ ] Should show preview of email on right side
- [ ] Should be pre-filled with the most recent freshsheet data (if available)
- [ ] Saving the form creates the latest "freshsheet"
- [ ] A freshsheet is not required to be made each day
- [ ] How often should we email freshsheets out? This could be a button that hugh can click -- or we can submit the freshsheet to everyone only upon change?

**Comment by BrendanMyers88** [comment]
Done!
