### ISSUE TITLE
Create isNew @decorator for "newly added" category

### ISSUE THREAD

**Issue by BrendanMyers88** [BrendanMyers88/EverFresh#5]
Create a boolean check for an item that's newly added based on time since it was added to the fresh sheet. This should be True for 1 week, and then automatically become False when the time since adding it expires.

On Freshsheet creation, Newly added items should be automatically checked.

**Comment by ckcollab** [comment]
Should look something like this, for reference:

```python
class SomeModel(models.Model):
    # this makes it so you can call some_model.is_new instead of 
    # some_model.is_new()
    @property
    def is_new(self):
        return self.date_added > (now() - two_weeks)
```
